apiVersion: v1
kind: ConfigMap
metadata:
  name: common-config
  namespace: microservices
data:
  ENVIRONMENT: "production"
  LOG_LEVEL: "info"
  REDIS_HOST: "redis-service"
  KAFKA_BROKERS: "kafka-service:9092"
  TRACING_ENABLED: "true"
