version: '3.8'

services:
  app:
    build: .
    container_name: springboot-app
    ports:
      - "8080:8080"
    volumes:
      # - springboot-logs:/app/logs
      # - springboot-config:/app/config
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mydb
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=mypassword
    depends_on:
      - db
    networks:
      - spring-network
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

  db:
    image: postgres:14-alpine
    container_name: postgres-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    networks:
      - spring-network

volumes:
  # springboot-logs:
  # springboot-config:
  postgres-data:

networks:
  spring-network:
    driver: bridge